# mysql:
#   image: mysql
#   container_name: database
#   ports:
#     - 6666:3306
#   environment:
#     MYSQL_DATABASE: course
#     MYSQL_ROOT_PASSWORD: 123456

php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/course
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80

# docker exec -it php sh
# docker-php-ext-install pdo pdo_mysql
