# test:
#   image: laravel
#   container_name: ttt  
#   volumes:
#     - .:/var/www/default
#     - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
#   ports:
#     - 8080:80

php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/default
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80

# docker exec -it php sh
# docker-php-ext-install pdo pdo_mysql
